# Generated by Django 5.1.5 on 2025-02-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('Customer_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('Alt_Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=150)),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('Customer_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
    ]
