# Generated by Django 5.1.5 on 2025-02-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='Alt_Phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Phone_No',
            field=models.BigIntegerField(),
        ),
    ]
