# Generated by Django 5.1.5 on 2025-02-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0002_alter_customerdetails_alt_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('Material_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Material_Name', models.CharField(max_length=50)),
                ('Material_Make', models.CharField(max_length=50)),
                ('Material_Size_In_Meters', models.IntegerField()),
                ('Material_Size_In_Feet', models.IntegerField()),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
    ]
