# Generated by Django 5.1.5 on 2025-02-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0003_materialmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmaster',
            name='Additional_Info',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
