# Generated by Django 5.1.5 on 2025-02-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0005_alter_materialmaster_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardMaster',
            fields=[
                ('S_No', models.IntegerField(unique=True)),
                ('Inward_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Material_Id', models.CharField(max_length=50)),
                ('Vendor_Name', models.CharField(max_length=50)),
                ('Vendor_Mobile', models.IntegerField()),
                ('Vendor_GST', models.CharField(max_length=50)),
                ('Invoice_Cost', models.IntegerField()),
                ('Invoice_Quantity', models.IntegerField()),
                ('Batch_No', models.CharField(max_length=50)),
                ('Additional_Info', models.CharField(max_length=50)),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
    ]
