# Generated by Django 5.1.5 on 2025-02-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0006_inwardmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardmaster',
            name='Batch_Id',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
