# Generated by Django 5.1.5 on 2025-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0010_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categories_Id', models.CharField(max_length=50)),
                ('Categories_Name', models.CharField(max_length=50)),
                ('Product_Name', models.CharField(max_length=50)),
                ('Sub_Categories', models.CharField(max_length=50)),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('Product_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=50)),
                ('GST', models.CharField(max_length=50)),
                ('HSN_Code', models.CharField(max_length=50)),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
    ]
