# Generated by Django 5.1.5 on 2025-02-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0011_categoriesmaster_productmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesmaster',
            name='id',
        ),
        migrations.AlterField(
            model_name='categoriesmaster',
            name='Categories_Id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
