# Generated by Django 5.1.5 on 2025-02-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0012_remove_categoriesmaster_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostMaster',
            fields=[
                ('Cost_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=50)),
                ('Category_Name', models.CharField(max_length=50)),
                ('Sub_Category', models.CharField(max_length=50)),
                ('Cost_Per_Unit', models.IntegerField(default=0)),
                ('Cost_Per_Sqft', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
    ]
