# Generated by Django 5.1.5 on 2025-02-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0013_costmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='costmaster',
            name='Cost_Per_Sqft_Status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costmaster',
            name='Cost_Per_Unit_Status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costmaster',
            name='Cost_Per_Sqft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='costmaster',
            name='Cost_Per_Unit',
            field=models.IntegerField(null=True),
        ),
    ]
