# Generated by Django 5.1.5 on 2025-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0014_costmaster_cost_per_sqft_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesmaster',
            name='Sub_Categories',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='costmaster',
            name='Cost_Per_Sqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costmaster',
            name='Cost_Per_Unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costmaster',
            name='Sub_Category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
