# Generated by Django 5.1.5 on 2025-02-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0015_alter_categoriesmaster_sub_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingMaster',
            fields=[
                ('Bill_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Customer_Id', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('Product_Name', models.CharField(max_length=50)),
                ('Category_Name', models.CharField(max_length=50)),
                ('Sub_Category', models.CharField(max_length=50, null=True)),
                ('Length', models.IntegerField(default=0)),
                ('Width', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('Cost_Per_Quantity', models.IntegerField(default=0)),
                ('GST', models.CharField(max_length=50)),
                ('HSN_Code', models.CharField(max_length=50)),
                ('Total_Cost', models.CharField(max_length=50)),
                ('Total_Cost_With_Gst', models.CharField(max_length=50)),
            ],
        ),
    ]
