# Generated by Django 5.1.5 on 2025-02-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0016_billingmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmaster',
            name='Product_Id',
            field=models.CharField(default='PROD0001', max_length=50),
            preserve_default=False,
        ),
    ]
