# Generated by Django 5.1.5 on 2025-02-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0017_billingmaster_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingmaster',
            name='Product_Id',
        ),
    ]
