# Generated by Django 5.1.5 on 2025-02-21 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0019_estimatemaster_quotemaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimatemaster',
            old_name='Bill_Id',
            new_name='Estimation_Id',
        ),
        migrations.RenameField(
            model_name='quotemaster',
            old_name='Bill_Id',
            new_name='Quote_Id',
        ),
        migrations.RemoveField(
            model_name='billingmaster',
            name='Category_Name',
        ),
        migrations.RemoveField(
            model_name='billingmaster',
            name='Cost_Per_Quantity',
        ),
        migrations.RemoveField(
            model_name='billingmaster',
            name='GST',
        ),
        migrations.RemoveField(
            model_name='billingmaster',
            name='HSN_Code',
        ),
        migrations.RemoveField(
            model_name='billingmaster',
            name='Length',
        ),
        migrations.RemoveField(
            model_name='billingmaster',
            name='Product_Name',
        ),
        migrations.RemoveField(
            model_name='billingmaster',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='billingmaster',
            name='Sub_Category',
        ),
        migrations.RemoveField(
            model_name='billingmaster',
            name='Total_Cost',
        ),
        migrations.RemoveField(
            model_name='billingmaster',
            name='Total_Cost_With_Gst',
        ),
        migrations.RemoveField(
            model_name='billingmaster',
            name='Width',
        ),
        migrations.RemoveField(
            model_name='estimatemaster',
            name='Category_Name',
        ),
        migrations.RemoveField(
            model_name='estimatemaster',
            name='Cost_Per_Quantity',
        ),
        migrations.RemoveField(
            model_name='estimatemaster',
            name='HSN_Code',
        ),
        migrations.RemoveField(
            model_name='estimatemaster',
            name='Length',
        ),
        migrations.RemoveField(
            model_name='estimatemaster',
            name='Product_Name',
        ),
        migrations.RemoveField(
            model_name='estimatemaster',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='estimatemaster',
            name='Sub_Category',
        ),
        migrations.RemoveField(
            model_name='estimatemaster',
            name='Total_Cost',
        ),
        migrations.RemoveField(
            model_name='estimatemaster',
            name='Width',
        ),
        migrations.RemoveField(
            model_name='quotemaster',
            name='Category_Name',
        ),
        migrations.RemoveField(
            model_name='quotemaster',
            name='Cost_Per_Quantity',
        ),
        migrations.RemoveField(
            model_name='quotemaster',
            name='GST',
        ),
        migrations.RemoveField(
            model_name='quotemaster',
            name='HSN_Code',
        ),
        migrations.RemoveField(
            model_name='quotemaster',
            name='Length',
        ),
        migrations.RemoveField(
            model_name='quotemaster',
            name='Product_Name',
        ),
        migrations.RemoveField(
            model_name='quotemaster',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='quotemaster',
            name='Sub_Category',
        ),
        migrations.RemoveField(
            model_name='quotemaster',
            name='Total_Cost',
        ),
        migrations.RemoveField(
            model_name='quotemaster',
            name='Total_Cost_With_Gst',
        ),
        migrations.RemoveField(
            model_name='quotemaster',
            name='Width',
        ),
        migrations.AddField(
            model_name='billingmaster',
            name='Grand_Total',
            field=models.IntegerField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimatemaster',
            name='Grand_Total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotemaster',
            name='Grand_Total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('Product_Name', models.CharField(max_length=50)),
                ('Category_Name', models.CharField(max_length=50)),
                ('Sub_Category', models.CharField(max_length=50, null=True)),
                ('Length', models.IntegerField(default=0)),
                ('Width', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('Cost_Per_Quantity', models.IntegerField(default=0)),
                ('GST', models.CharField(max_length=50)),
                ('HSN_Code', models.CharField(max_length=50)),
                ('Total_Cost', models.CharField(max_length=50)),
                ('Total_Cost_With_Gst', models.CharField(max_length=50)),
                ('Bill_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssdapp.billingmaster')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('Product_Name', models.CharField(max_length=50)),
                ('Category_Name', models.CharField(max_length=50)),
                ('Sub_Category', models.CharField(max_length=50, null=True)),
                ('Length', models.IntegerField(default=0)),
                ('Width', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('Cost_Per_Quantity', models.IntegerField(default=0)),
                ('HSN_Code', models.CharField(max_length=50)),
                ('Total_Cost', models.CharField(max_length=50)),
                ('Estimation_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssdapp.estimatemaster')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('Product_Name', models.CharField(max_length=50)),
                ('Category_Name', models.CharField(max_length=50)),
                ('Sub_Category', models.CharField(max_length=50, null=True)),
                ('Length', models.IntegerField(default=0)),
                ('Width', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('Cost_Per_Quantity', models.IntegerField(default=0)),
                ('GST', models.CharField(max_length=50)),
                ('HSN_Code', models.CharField(max_length=50)),
                ('Total_Cost', models.CharField(max_length=50)),
                ('Total_Cost_With_Gst', models.CharField(max_length=50)),
                ('Quote_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssdapp.quotemaster')),
            ],
        ),
    ]
