# Generated by Django 5.1.5 on 2025-02-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0020_rename_bill_id_estimatemaster_estimation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmaster',
            name='Grand_Total',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='estimatemaster',
            name='Grand_Total',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quotemaster',
            name='Grand_Total',
            field=models.IntegerField(default=1),
        ),
    ]
