# Generated by Django 5.1.5 on 2025-02-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0021_alter_billingmaster_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmaster',
            name='Grand_Total',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estimatemaster',
            name='Grand_Total',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quotemaster',
            name='Grand_Total',
            field=models.CharField(max_length=50),
        ),
    ]
