# Generated by Django 5.1.5 on 2025-02-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0022_alter_billingmaster_grand_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingmaster',
            name='Grand_Total',
        ),
        migrations.RemoveField(
            model_name='estimatemaster',
            name='Grand_Total',
        ),
        migrations.RemoveField(
            model_name='quotemaster',
            name='Grand_Total',
        ),
    ]
