# Generated by Django 5.1.5 on 2025-02-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0023_remove_billingmaster_grand_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatedetails',
            name='Estimation_Id',
        ),
        migrations.RemoveField(
            model_name='quotedetails',
            name='Quote_Id',
        ),
        migrations.DeleteModel(
            name='BillingDetails',
        ),
        migrations.DeleteModel(
            name='BillingMaster',
        ),
        migrations.DeleteModel(
            name='EstimateDetails',
        ),
        migrations.DeleteModel(
            name='EstimateMaster',
        ),
        migrations.DeleteModel(
            name='QuoteDetails',
        ),
        migrations.DeleteModel(
            name='QuoteMaster',
        ),
    ]
