# Generated by Django 5.1.5 on 2025-02-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0026_remove_estimatedetails_estimation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingMaster',
            fields=[
                ('Bill_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Customer_Id', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstimateMaster',
            fields=[
                ('Estimation_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Customer_Id', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuoteMaster',
            fields=[
                ('Quote_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Customer_Id', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('Product_Name', models.CharField(max_length=50)),
                ('Category_Name', models.CharField(max_length=50)),
                ('Sub_Category', models.CharField(max_length=50, null=True)),
                ('Length', models.IntegerField(default=0)),
                ('Width', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('Cost_Per_Quantity', models.IntegerField(default=0)),
                ('GST', models.CharField(max_length=50)),
                ('HSN_Code', models.CharField(max_length=50)),
                ('Total_Cost', models.CharField(max_length=50)),
                ('Total_Cost_With_Gst', models.CharField(max_length=50)),
                ('Bill_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssdapp.billingmaster')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('Product_Name', models.CharField(max_length=50)),
                ('Category_Name', models.CharField(max_length=50)),
                ('Sub_Category', models.CharField(max_length=50, null=True)),
                ('Length', models.IntegerField(default=0)),
                ('Width', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('Cost_Per_Quantity', models.IntegerField(default=0)),
                ('HSN_Code', models.CharField(max_length=50)),
                ('Total_Cost', models.CharField(max_length=50)),
                ('Estimation_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssdapp.estimatemaster')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('Product_Name', models.CharField(max_length=50)),
                ('Category_Name', models.CharField(max_length=50)),
                ('Sub_Category', models.CharField(max_length=50, null=True)),
                ('Length', models.IntegerField(default=0)),
                ('Width', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('Cost_Per_Quantity', models.IntegerField(default=0)),
                ('GST', models.CharField(max_length=50)),
                ('HSN_Code', models.CharField(max_length=50)),
                ('Total_Cost', models.CharField(max_length=50)),
                ('Total_Cost_With_Gst', models.CharField(max_length=50)),
                ('Quote_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssdapp.quotemaster')),
            ],
        ),
    ]
