# Generated by Django 5.1.5 on 2025-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0027_billingmaster_estimatemaster_quotemaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmaster',
            name='Grand_Total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimatemaster',
            name='Grand_Total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotemaster',
            name='Grand_Total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
