# Generated by Django 5.1.5 on 2025-02-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0028_billingmaster_grand_total_estimatemaster_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='Custom_Product',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimatedetails',
            name='Custom_Product',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotedetails',
            name='Custom_Product',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
