# Generated by Django 5.1.5 on 2025-02-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0029_billingdetails_custom_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatedetails',
            name='HSN_Code',
        ),
    ]
