# Generated by Django 5.1.5 on 2025-02-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0030_remove_estimatedetails_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmaster',
            name='Grand_Total_With_Gst',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotemaster',
            name='Grand_Total_With_Gst',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
