# Generated by Django 5.1.5 on 2025-02-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0031_billingmaster_grand_total_with_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='Phone_No',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='estimatedetails',
            name='Phone_No',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='estimatemaster',
            name='Phone_No',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='Phone_No',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='quotemaster',
            name='Phone_No',
            field=models.BigIntegerField(),
        ),
    ]
