# Generated by Django 5.1.5 on 2025-02-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0032_alter_billingdetails_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmaster',
            name='Phone_No',
            field=models.BigIntegerField(),
        ),
    ]
