# Generated by Django 5.1.5 on 2025-02-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0033_alter_billingmaster_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='billingmaster',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='estimatedetails',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='estimatemaster',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotedetails',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotemaster',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
