# Generated by Django 5.1.5 on 2025-02-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0037_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
