# Generated by Django 5.1.5 on 2025-02-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0038_employee_address'),
    ]

    operations = [
       
        
       
      
       
       
        
       
       
       
    ]
