# Generated by Django 5.1.5 on 2025-02-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0039_billingdetails_final_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmaster',
            name='Size',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        )
    ]
