# Generated by Django 5.1.5 on 2025-02-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0040_billingdetails_final_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='Final_Total_Cost',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='Final_Total_Cost_With_Gst',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='Item_Id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='Modified_Cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='Total_Sqft',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='costmaster',
            name='Fixed_Cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costmaster',
            name='Fixed_Cost_Status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estimatedetails',
            name='Final_Total_Cost',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimatedetails',
            name='Item_Id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimatedetails',
            name='Modified_Cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='estimatedetails',
            name='Total_Sqft',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quotedetails',
            name='Final_Total_Cost',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotedetails',
            name='Final_Total_Cost_With_Gst',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotedetails',
            name='Item_Id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotedetails',
            name='Modified_Cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quotedetails',
            name='Total_Sqft',
            field=models.IntegerField(null=True),
        ),
    ]
