# Generated by Django 5.1.5 on 2025-02-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0041_billingdetails_final_total_cost_and_more'),
    ]

    operations = [
    ]
