# Generated by Django 5.1.5 on 2025-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0042_auto_20250225_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costmaster',
            name='Fixed_Cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='costmaster',
            name='Fixed_Cost_Status',
            field=models.IntegerField(default=1),
        ),
    ]
