# Generated by Django 5.1.5 on 2025-02-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0043_alter_costmaster_fixed_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costmaster',
            name='Fixed_Cost',
        ),
        migrations.RemoveField(
            model_name='costmaster',
            name='Fixed_Cost_Status',
        ),
    ]
