# Generated by Django 5.1.5 on 2025-02-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0044_remove_costmaster_fixed_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costmaster',
            name='Fixed_Cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='costmaster',
            name='Fixed_Cost_Status',
            field=models.IntegerField(default=1),
        ),
    ]
