# Generated by Django 5.1.5 on 2025-02-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0045_costmaster_fixed_cost_costmaster_fixed_cost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costmaster',
            name='Fixed_Cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costmaster',
            name='Fixed_Cost_Status',
            field=models.IntegerField(default=0),
        ),
    ]
