# Generated by Django 5.1.5 on 2025-02-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0046_alter_costmaster_fixed_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costmaster',
            name='Size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
