# Generated by Django 5.1.5 on 2025-02-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0047_costmaster_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesmaster',
            name='Size',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='costmaster',
            name='Size',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
    ]
