# Generated by Django 5.1.5 on 2025-02-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0048_alter_categoriesmaster_size_alter_costmaster_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotedetails',
            name='Modified_Cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
