# Generated by Django 5.1.5 on 2025-02-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0049_alter_quotedetails_modified_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotedetails',
            name='Modified_Cost',
        ),
    ]
