# Generated by Django 5.1.5 on 2025-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0050_remove_quotedetails_modified_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedetails',
            name='Modified_Cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
