# Generated by Django 5.1.5 on 2025-02-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0052_remove_quotedetails_final_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedetails',
            name='Final_Total_Cost',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
