# Generated by Django 5.1.5 on 2025-02-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0053_quotedetails_final_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotedetails',
            name='Final_Total_Cost_With_Gst',
        ),
    ]
