# Generated by Django 5.1.5 on 2025-02-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0054_remove_quotedetails_final_total_cost_with_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedetails',
            name='Final_Total_Cost_With_Gst',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
