# Generated by Django 5.1.5 on 2025-02-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0055_quotedetails_final_total_cost_with_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='Remarks',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimatedetails',
            name='Remarks',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotedetails',
            name='Remarks',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
