# Generated by Django 5.1.5 on 2025-02-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0056_billingdetails_remarks_estimatedetails_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='Size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimatedetails',
            name='Size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotedetails',
            name='Size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
