# Generated by Django 5.1.5 on 2025-02-28 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0057_billingdetails_size_estimatedetails_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Master',
            fields=[
                ('Payment_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Total_Amount', models.IntegerField()),
                ('Paid_Amount', models.IntegerField()),
                ('Pending_Amount', models.IntegerField()),
                ('Fully_Paid', models.IntegerField(default=0)),
                ('Partialy_Paid', models.IntegerField(default=0)),
                ('Not_Paid', models.IntegerField(default=1)),
                ('Force_Paid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Mode', models.CharField(max_length=50)),
                ('Utr_Or_Reason', models.CharField(max_length=50)),
                ('Mobile_No', models.CharField(max_length=50)),
                ('Pending_Amount', models.IntegerField()),
                ('Payment_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssdapp.payment_master')),
            ],
        ),
    ]
