# Generated by Django 5.1.5 on 2025-02-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0058_payment_master_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_master',
            name='Paid_Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment_master',
            name='Pending_Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment_master',
            name='Total_Amount',
            field=models.IntegerField(default=0),
        ),
    ]
