# Generated by Django 5.1.5 on 2025-02-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0059_alter_payment_master_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='Pending_Amount',
            field=models.IntegerField(default=0),
        ),
    ]
