# Generated by Django 5.1.5 on 2025-02-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0060_alter_payment_details_pending_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_master',
            old_name='Force_Paid',
            new_name='Grand_Total',
        ),
        migrations.RemoveField(
            model_name='payment_master',
            name='Fully_Paid',
        ),
        migrations.RemoveField(
            model_name='payment_master',
            name='Not_Paid',
        ),
        migrations.RemoveField(
            model_name='payment_master',
            name='Paid_Amount',
        ),
        migrations.RemoveField(
            model_name='payment_master',
            name='Partialy_Paid',
        ),
        migrations.RemoveField(
            model_name='payment_master',
            name='Pending_Amount',
        ),
        migrations.RemoveField(
            model_name='payment_master',
            name='Total_Amount',
        ),
        migrations.AddField(
            model_name='payment_details',
            name='Force_Paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='Fully_Paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='Grand_Total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='Not_Paid',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='Paid_Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='Partialy_Paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='Payment_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
