# Generated by Django 5.1.5 on 2025-02-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0061_rename_force_paid_payment_master_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_master',
            name='Pending_Amount',
            field=models.IntegerField(default=0),
        ),
    ]
