# Generated by Django 5.1.5 on 2025-03-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0062_payment_master_pending_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_master',
            name='Paid_Amount',
            field=models.IntegerField(default=0),
        ),
    ]
