# Generated by Django 5.1.5 on 2025-03-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0064_remove_payment_details_force_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_master',
            name='Force_Paid',
        ),
        migrations.RemoveField(
            model_name='payment_master',
            name='Fully_Paid',
        ),
        migrations.RemoveField(
            model_name='payment_master',
            name='Not_Paid',
        ),
        migrations.RemoveField(
            model_name='payment_master',
            name='Partialy_Paid',
        ),
        migrations.AddField(
            model_name='billingmaster',
            name='Force_Paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingmaster',
            name='Fully_Paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingmaster',
            name='Not_Paid',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='billingmaster',
            name='Partialy_Paid',
            field=models.IntegerField(default=0),
        ),
    ]
