# Generated by Django 5.1.5 on 2025-03-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0065_remove_payment_master_force_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_details',
            name='Bill_Id',
            field=models.CharField(default='BILL0001', max_length=50),
        ),
    ]
