# Generated by Django 5.1.5 on 2025-03-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0066_payment_details_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_master',
            name='Bill_Id',
            field=models.CharField(default='BILL0001', max_length=50),
        ),
    ]
