# Generated by Django 5.1.5 on 2025-03-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0067_payment_master_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmaster',
            name='Paid_Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingmaster',
            name='Pending_Amount',
            field=models.IntegerField(default=0),
        ),
    ]
